apiVersion: v1
kind: PersistentVolume
metadata:
  name: asterisk-recordings-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: my-gce-disk
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-logs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: my-gce-disk
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asterisk-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  gcePersistentDisk:
    pdName: my-gce-disk
    fsType: ext4
