apiVersion: v1
kind: Service
metadata:
  name: asterisk-numbers-service
spec:
  selector:
    app: asterisk-numbers
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort