from . import sip
from . import asterisk_server
from . import phone_common
from . import res_users
from . import res_partner
from . import logs
from . import asterisk_queue
from . import sms
from . import evenlistnner
from . import dashborad