apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1 #Change This Base On Scalibality
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      nodeSelector:
        node-role: node2
      containers:
      - name: postgres
        image: postgres:15
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: POSTGRES_USER
            value: odoo
          - name: POSTGRES_PASSWORD
            value: odoo
        ports:
          - containerPort: 5432